app/config/routes.rb
App::Application.routes.draw do
  resources :questions

  root :to => 'questions#index'

end

app/app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :answer1, :answer2, :answer3, :answer4, :correct, :description
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/app/controllers/generate_xml_controller.rb
class GenerateXmlController < ApplicationController
  def GenerateQuestions
    
  end
end

app/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/generate_xml_helper.rb
module GenerateXmlHelper
end

app/app/helpers/home_helper.rb
module HomeHelper
end

app/app/helpers/questions_helper.rb
module QuestionsHelper
  def GenerateXML

  end
end

app/app/views/home/index.html.erb
<!--<h1>Home#index</h1>
#<p>Find me in app/views/home/index.html.erb</p>-->
<h1>Level 1 Questions</h1>
<%= link_to "Manage", questions_path %>

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :answer1 %><br />
    <%= f.text_field :answer1 %>
  </div>
  <div class="field">
    <%= f.label :answer2 %><br />
    <%= f.text_field :answer2 %>
  </div>
  <div class="field">
    <%= f.label :answer3 %><br />
    <%= f.text_field :answer3 %>
  </div>
  <div class="field">
    <%= f.label :answer4 %><br />
    <%= f.text_field :answer4 %>
  </div>
  <div class="field">
    <%= f.label :correct %><br />
    <%= f.number_field :correct %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table class="tblQuestion">
  <tr>
    <th>Question</th>
    <th>Answer1</th>
    <th>Answer2</th>
    <th>Answer3</th>
    <th>Answer4</th>
    <th>Correct</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.description %></td>
    <td><%= question.answer1 %></td>
    <td><%= question.answer2 %></td>
    <td><%= question.answer3 %></td>
    <td><%= question.answer4 %></td>
    <td><%= question.correct %></td>
    <td><%= link_to(image_tag("view.gif"),question)  %></td>
    <td><%= link_to image_tag("edit.png"), edit_question_path(question) %></td>
    <td><%= link_to image_tag("delete.png"), question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>    <br>  <br>
<%=  button_to_function "Generate XML" %>

app/app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @question.description %>
</p>

<p>
  <b>Answer1:</b>
  <%= @question.answer1 %>
</p>

<p>
  <b>Answer2:</b>
  <%= @question.answer2 %>
</p>

<p>
  <b>Answer3:</b>
  <%= @question.answer3 %>
</p>

<p>
  <b>Answer4:</b>
  <%= @question.answer4 %>
</p>

<p>
  <b>Correct:</b>
  <%= @question.correct %>
</p>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>